### ISSUE TITLE
Check compatibility with Social Warfare plugin

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/components#30]
Assuring compatibility of [Social Warfare](https://wordpress.org/plugins/social-warfare/) plugin with Pixelgrade's Themes

**Vasco, Felt, Julia** — the share buttons from Social Warfare are not displayed at all

**Hive, Gema, Patch, Silk** — the share buttons from Social Warfare are displayed, with some issues:
- the buttons are displayed at [the top of the Single Post](https://cl.ly/3L1h3V3Q3T0Q), even if the plugins settings [look like this](https://cl.ly/1I0H312W2J3S) 
- with _Gema_, the buttons [take the link color](https://cl.ly/040p2e0p3h0u)

**Comment by vladolaru** [comment]
@alinclamba I have fixed the display issue for Vasco, Felt and Julia (it was a components fix).

**Comment by alinclamba** [comment]
We have an article about this now:

→ https://pixelgrade.com/docs/social-networks/adding-share-buttons-using-social-warfare/

Everything's ok now, so I'm going to close the issue. 
Thanks for the help @vladolaru.
