### ISSUE TITLE
[Docs] Decide on the best way to handle documentation

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/components#9]
Before building the project documentation, we should decide on the best way to do it in line with it being an open source project.

I could be:
1. a readme (a very long one)
2. an introductory readme and a GitHub wiki
3. an introductory readme and a static-generated Github Pages site (Jekyll)
4. a section in our guides.pixelgrade.com

I would be more inclined to go with version 2 as it is the most likely to allow for community contributions to the docs. Although version 3 is also within reach as long as the flow is clear.

**Comment by vladolaru** [comment]
Dupa o discutie cu @razwan inclin sa merg pe varianta unui readme de getting started si un wiki.

**Comment by vladolaru** [comment]
I will gather here some resources that I think are valuable to reaching a good helpful structure and scope:
- https://github.com/PharkMillups/beautiful-docs
- https://www.ybrikman.com/writing/2014/05/05/you-are-what-you-document/

**Comment by vladolaru** [comment]
I've decided to use the template and structure Facebook uses for their open source projects: GitHub Pages + Jekyll. I like their structure, the fact that it gives us a nice head start and also the right amount of features like the landing page, docs, blog, search.

The workflow is pretty easy (just edit and push) and it is flexible enough for all kinds of contributors. Non-technical contributors can use tools like prose.io (http://prose.io/#pixelgrade/components/tree/master/docs/_docs) or the Github editor (there are links at the end of each page) and technical people can run the site locally and use IDEs like PHPStorm to help them along.

**Comment by georgeolaru** [comment]
@vladolaru that looks neat!

**Comment by vladolaru** [comment]
Thanks @georgeolaru. The starting point is here: https://pixelgrade.github.io/components/ (ignore the fact that right now it is the documentation for a Facebook project, with a logo I mustered - I couldn't find the bare bones template).

**Comment by vladolaru** [comment]
I will close this since I have reached a decision so there is no point in keeping it open.
